### ISSUE TITLE
能否说明下如何在浮动窗口实现补全( ﹡ˆoˆ﹡ )

### ISSUE THREAD

**Issue by Leiyi548** [jayli/vim-easycomplete#118]

**Comment by jayli** [comment]
只要安装了 vim-easycomplete 浮动窗口内支持了补全的，不用特别配什么

![](https://gw.alicdn.com/imgextra/i1/O1CN01EECGEg1fMqD078CX2_!!6000000003993-2-tps-1893-1010.png)

**Comment by Leiyi548** [comment]
我想自己弄点补全的东西，我搞不明白浮动窗口怎么弄补全，请指教下

**Comment by jayli** [comment]
最简单的你绑定completefunc 函数就可以了，你`:h completefunc`看下文档，很详细

**Comment by Leiyi548** [comment]
@jayli 我看了下你写的代码，没看到你用这个函数实现补全，请指教下

**Comment by jayli** [comment]
我的实现比较复杂，我是监听了两个事件，一个是首次触发匹配动作的 TextChangedI 事件，如果首次匹配完成后，随后输入就 匹配 TextChangedP 事件，这两个事件偶尔会重复触发，需要做过滤。

TextChangedI
https://github.com/jayli/vim-easycomplete/blob/master/autoload/easycomplete.vim#L1697

TextChangedP
https://github.com/jayli/vim-easycomplete/blob/master/autoload/easycomplete.vim#L1706

监听两个事件的目的主要是提高匹配速度，因为 lsp 结果回调需要一些时间，手指敲键盘很快的话匹配结果会跟不上输入速度，会非常卡顿。所以用两个事件来分别执行 lsp 请求和本地查找，这样速度比较快。

如果你只需实现比较单一的语言补全的话，我觉得不用这么复杂，直接绑定 completefunc 函数，这个函数是通过 `<C-X><C-U>` 来触发，你只需添加一个 inoremap 把符合条件的输入情形匹配至 `<C-X><C-U>` 就可以了。

**Comment by Leiyi548** [comment]
@jayli 我不需要这么复杂，其实我就是想搞一个vim输入法，就是我将我所有的数据放在字典里，对应的key值输出数据
比如a对应 啊就会显示出来然后能选择打出。

**Comment by jayli** [comment]
那就绑定 completefunc 函数就可以，添加一个 inoremap 把符合条件的输入情形匹配至 `<C-X><C-U>` 就可以了

**Comment by Leiyi548** [comment]
@jayli 大佬我看了下，他是列表实现
用字典我不知道怎么写，你能写个简单的让我看看吗🙏🏻

**Comment by jayli** [comment]
你可以参照这个，他实现的比较简单 

https://github.com/vimlab/vim-nodecompl/blob/master/plugin/nodecompl.vim

你看下他实现的这个函数 nodecompl#complete
