### ISSUE TITLE
如何将回车键进行确认的映射取消掉？

### ISSUE THREAD

**Issue by xiaoqixian** [jayli/vim-easycomplete#123]
我希望的是直接通过tab选择就可以了，选好后就可以直接空格或者回车，但是现在回车键会确认选择，需要按两次回车才能到下一行，请问有没有什么办法取消呢？

**Comment by jayli** [comment]
按照我以往的习惯，选中后回车应该是选中的动作，没想好如果不是回车确认，需要用什么来代替。

另外，选中状态时继续敲字符，这时有两个选择，一个是继续本次匹配，一个是关闭匹配菜单，我这里选择了第一种，两种怎么做兼容还没想好。

你试着绑定 c-p 或者 c-n 来做选择

**Comment by jayli** [comment]
先later掉

**Comment by seflerZ** [comment]
支持，使用回车会打断现有的撰写。
