### ISSUE TITLE
E716: Key not present in Dictionary: "name"

### ISSUE THREAD

**Issue by yao-aiqing** [jayli/vim-easycomplete#125]
![image](https://user-images.githubusercontent.com/58630259/143998347-197a541e-8bf7-4e14-89ae-d2d29918d7c6.png)
我的安装环境是:[root@VM-0-15-centos ~]# uname -a
Linux VM-0-15-centos 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
报错的命令是：`EasyCompleteInstallServer `

**Comment by jayli** [comment]
已经修复，加上了提示

你应该是在支持 lsp 的文件类型下执行这个命令。
