### ISSUE TITLE
函数自动补全自动增加括号

### ISSUE THREAD

**Issue by liwnn** [jayli/vim-easycomplete#127]
![image](https://user-images.githubusercontent.com/4005513/149270630-181f2934-a005-4253-8d10-34d18ce249fe.png)
自动补全函数能不能只增加一个左括号？如何配置？ 或者可以让光标在两个括号之间？

**Comment by liwnn** [comment]
确实，按enter后会变化。这跟我之前的插件习惯有关。
之前是这么用的：1、直接C-N选择 2、不按enter，直接编辑

**Comment by jayli** [comment]
我是这么实现的，基本上完全遵循了 lsp 的 TextEdit 的实现，即 lsp 返回的匹配完整的结构，插入位置标识出来，这些信息都给在 TextEdit 中一并返回，因此除了你这个case `fmt.Fprintf(|)`之外，还有两种情况比较常见，第一种是函数包含多参数的展开（我这里简化实现了），比如 `console.log($param1, $param2, $param3)`，然后光标定位在其中一个参数，第二种是 snip 的展开，这个需要针对每个 lsp 做单独处理，兼容处理太复杂，我索性就摈弃了，snip 完全基于 `vim-snippets` 来做了。

对于你这个case，需要针对函数展开的情况做 hack，比如需要显示一个完整 snip 的一半，基本上没办法用通用逻辑来实现，除了函数左括号的起始位置外，还有数组左方括号起始位置，集合左括号起始位置，对象左花括号起始位置，箭头函数的起始位置，c++中的双冒号的起始位置等等，我暂时还做不到枚举穷尽，所以直接使用了lsp规范的标准实现。

如果这个操作对你影响很大的话，你可以fork下代码看看有没有好的修改建议，期待你的建议。

**Comment by jayli** [comment]
感谢你的建议，我考虑一下。vim 的 complete menu 中按 `<up>` 和 `<down>` 应该是你要的效果，我习惯 tab 补全，所以我看下能够兼容你的说的情况。

你可以直接修改下代码来达到你想要的效果

https://github.com/jayli/vim-easycomplete/blob/master/autoload/easycomplete.vim#L959  这里的`"\<C-N>"` 修改为 `"\<Down>"`, https://github.com/jayli/vim-easycomplete/blob/master/autoload/easycomplete.vim#L1007 这里的 `"\<C-P>"`修改为`"\<Up>"`，再用 tab 切换匹配项时就不会触发编辑了。

**Comment by jayli** [comment]
先 later 掉
