### ISSUE TITLE
如何关闭警告提示

### ISSUE THREAD

**Issue by gitzhangzhao** [jayli/vim-easycomplete#131]
您好，我使用easycomplete代替一直使用的YCM，感觉真的很不错，但是有一个小问题：
1. 一般我不需要除C/CPP以外的其他补全，如何关闭这个警告，当我打开其他文件如.vimrc的提示：
```bash
'vim-language-server' is not avilable. Do ':InstallLspServer'
```
2. 我已经关闭了代码语法检查：let g:easycomplete_diagnostics_enable = 0，但当我打开C/CPP文件时还是会提示：
```bash
You should set Diagnostic jumping map-key manully. ...
```

应该如何关闭这些警告信息

**Comment by jayli** [comment]
你更新下代码，然后用这个配置：

`let g:easycomplete_lsp_checking = 0`

**Comment by gitzhangzhao** [comment]
@jayli 您好，我更新了代码并加入了配置，第一个警告信息已经不再发生。但是第二个警告仍然存在：
这是我的配置：
`
let g:easycomplete_diagnostics_enable = 0
let g:easycomplete_lsp_checking = 0
`
我关闭了代码的语法检测，但是在打开任意文件时仍然会提示这个警告：
`>>> You should set Diagnostic jumping map-key manully . ':h easycomplete' for help`

我认为我已经关闭了语法检测，应该不需要再去配置跳转键位

但是如果我重新映射了跳转按键，我发现也没有用，提示信息仍然会出现：
`nnoremap <silent> <C-w> :EasyCompleteNextDiagnostic<CR>
nnoremap <silent> <C-e> :EasyCompletePreviousDiagnostic<CR>`

**Comment by jayli** [comment]
你绑定了 c-k 和 c-j 作为他用，这个绑定有冲突所以我给了个提示，我以为这个提示不常见，现在我加上过滤了

你直接更新代码就好了。

```vim
let g:easycomplete_diagnostics_enable = 0
let g:easycomplete_lsp_checking = 0
```

**Comment by gitzhangzhao** [comment]
@jayli ok，非常感谢~
