### ISSUE TITLE
Adding R Markdown for R completion

### ISSUE THREAD

**Issue by fasterius** [jayli/vim-easycomplete#174]
I'm currently trying out your plugin, and it looks very nice so far - thanks a lot for you effort! I code a lot in R, but do so inside R Markdown (`filetype = rmarkdown`, extensions `.Rmd` and `.rmd`). Getting the `r-languageserver` to work in normal R scripts works just fine, but I also want it to work inside R Markdown files.

I assume I have to change the `allowlist` or something similar, but I cannot find out how to do it in the documentation. Any help?

**Comment by jayli** [comment]
I fixed it. You can update vim-easycomplete. `rmd` and `rmarkdown` filetypes are supported by default.

After updating. You can add missing filetypes via `g:easycomplete_filetypes`:

```
let g:easycomplete_filetypes = {
      \   "sh": {
      \     "whitelist": ["shell"]
      \   },
      \   "r": {
      \     "whitelist": ["rmd", "rmarkdown"]
      \   },
      \ }
```

**Comment by fasterius** [comment]
Thanks, that works perfectly!
