### ISSUE TITLE
InstallServer for ccls only works using brew

### ISSUE THREAD

**Issue by 0xDagal** [jayli/vim-easycomplete#175]
I am coming from [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and because of [this](https://github.com/codota/tabnine-vim/issues/100#issuecomment-1050835933) I wanted to test [vim-easycomplete](https://github.com/jayli/vim-easycomplete).

I sometine code in C and wanted to install the LS for it so I opened a file in C and typed `:EasyCompleteInstallServer` but it did not work so I checked the `cpp.sh` file and seen

```sh
#!/usr/bin/env bash

set -e

brew install ccls
```

So it will not work on any OS other than those using `brew`

**Comment by jayli** [comment]
Thank you for reporting. I replaced ccls with clangd witch is easier to install. Please update vim-easycomplete.
