### ISSUE TITLE
clash with nvim-lsp-installer

### ISSUE THREAD

**Issue by g2boojum** [jayli/vim-easycomplete#190]
I recently installed vim-easycomplete, and I really appreciate the no-configuration-required philosophy. It seems to be working quite well. I did notice that I've been asked to install lsp servers that I knew I'd already installed, and I realized that vim-easycomplete doesn't seem to be taking advantage of the fact that I have nvim-lsp-installer installed (and configured). Is the expectation that I should be using vim-easycomplete to install the lsp servers instead?

Thanks for a lovely plugin!

**Comment by jayli** [comment]
Good idea. I'll think about supporting this feature. 🥇

**Comment by jayli** [comment]
- [ ] ts
- [ ] lua
- [ ] deno
- [ ] tn
- [ ] vim
- [ ] cpp
- [ ] css
- [ ] html
- [ ] yml
- [ ] xml
- [ ] sh
- [ ] json
- [ ] php
- [ ] dart
- [ ] py
- [ ] java
- [ ] go
- [ ] r
- [ ] rb
- [ ] nim
- [ ] rust
- [ ] kt
- [ ] grvy
- [ ] cmake
- [ ] c#

**Comment by jayli** [comment]
I've solved this issue. It's compatible with nvim-lsp-installer.

**Comment by g2boojum** [comment]
Much appreciated!
