### ISSUE TITLE
iskeyword

### ISSUE THREAD

**Issue by martineausimon** [jayli/vim-easycomplete#210]
Hi ! Is there a way to use `iskeyword` function for dictionary completion ?
I have the following lines in my `init.lua` but it doesn't work :
```lua
vim.opt.iskeyword:append("-")
vim.opt.iskeyword:append([[\]])
```

**Comment by jayli** [comment]
Please update the plugin and try again.

**Comment by martineausimon** [comment]
Thanks, it works perfectly !
