### ISSUE TITLE
Clangd 开启过多导致系统内存耗尽

### ISSUE THREAD

**Issue by keeferwu** [jayli/vim-easycomplete#222]
在VIM 中每打开一个c文件就会新建一个 clangd 的进程，导致系统内存被耗尽

![image](https://user-images.githubusercontent.com/61483526/185307214-03707f68-c346-4d87-98a5-e6bace749a2e.png)

![image](https://user-images.githubusercontent.com/61483526/185306149-8be17e24-c752-42e1-98c9-936ca878610e.png)

**Comment by qifeng-git** [comment]
调试发现：
 vim 每打开一个buffer，插件都会执行 RegisterLspServer 来注册 cpp， 这时系统中就会多出一个 clangd 的process

是否有方法做到 当buffer 没有在使用时，能够注销掉 buffer 对应的 clangd process？

**Comment by jayli** [comment]
的确是个问题，退出 buf 时应该销毁，我搞一下

**Comment by qifeng-git** [comment]
内存消耗太惊人了，等不及作者修复，自己稍微做了一些调整，不清楚是不是对其他功能有影响，先这么用吧

![图片](https://user-images.githubusercontent.com/61483526/191881749-bbc25787-cb65-4060-b4b2-eaf77ebac589.png)

**Comment by qifeng-git** [comment]
像clangd 这种常驻进程，应该在vim打开的时候，创建一次就好，不应该跟着buffer去创建

**Comment by qifeng-git** [comment]
在 lsp.vim 文件中加了return 就没有该问题了，不知道是不是一个bug：
![图片](https://user-images.githubusercontent.com/61483526/192125677-6e510164-06a6-439f-862c-2d4130a1e856.png)

**Comment by jayli** [comment]
暂时修复了 cpp 的问题
