### ISSUE TITLE
Easycomplete does not work well with C 

### ISSUE THREAD

**Issue by fengyd2006** [jayli/vim-easycomplete#227]
When I open c file, enter some characters,  the matched words will be listed and can be selected.
But when I jump to another file with ctrl + ] to check some functions which define on another file, later jump back to the original file with ctrl + O, then enter some characters,  the matched words will not be listed any more. 
Could you help check it?

**Comment by hdante** [comment]
Hello, is this bug the same as yours ?

1) Move cursor to `printf`
2) `Control+]`, `Control+t`, `Control+]`
3) Gets stuck with message ¨Retrieving definition..." at the status bar and doesn't reopen the `printf()` definition.

**Comment by jayli** [comment]
maybe it's a bug
