### ISSUE TITLE
snippets的tab受上一行内容影响

### ISSUE THREAD

**Issue by linyaotang** [jayli/vim-easycomplete#231]
![image](https://user-images.githubusercontent.com/98246172/220862058-ca0c8dc6-e027-4c06-ac95-7539c73dbc0d.png)
如图，test映射了一段代码
每次test时，会受到上一行内容影响，如上图中3-9行，只有第7行因为第6行对应字符为空，执行成功；其他行如第9行受第8行影响，按下tab后，变成testa空格空格空格，这个"a"根据规律来自于第8行的c'a'll；第8行变成testb，b来自于a'b'stract

使用snippets+snipmate  snippet+ultisnip时均没有问题

**Comment by zsccll** [comment]
我也发现了这个问题

**Comment by jayli** [comment]
你再更新下插件试试

**Comment by linyaotang** [comment]
嗯哼，收到谢谢~

**Comment by linyaotang** [comment]
更新后更不能用了，tab都没snipmate的显示了，囧

另外爆了lua的错误

 

发件人: ***@***.*** ***@***.*** 代表 lijing00333
发送时间: 2023年12月5日 13:54
收件人: jayli/vim-easycomplete
抄送: tanglinyao; Author
主题: Re: [jayli/vim-easycomplete] snippets的tab受上一行内容影响 (Issue #231)

 

你再更新下插件试试
