### ISSUE TITLE
请问lint在那些语言里实现了？因为试了好几个server以及用linteasycomplete都没有什么效果

### ISSUE THREAD

**Issue by peterzhu1992** [jayli/vim-easycomplete#234]
如题，感谢这个插件，虽然windows支持一般但我还是让好几个跑起来了。
就是搞不清楚怎么弄lint，因为貌似readme写了说是有的lint，就是没看到在哪里。

谢谢！

**Comment by jayli** [comment]
文档里的最后部分有一些例子：

<https://github.com/jayli/vim-easycomplete#more-examples>

lint 其实就是 lsp 的 diagnostics.
