### ISSUE TITLE
超过一万行的lua文件开启插件后极易卡住

### ISSUE THREAD

**Issue by WisdomCui** [jayli/vim-easycomplete#239]
操作系统:macOS 12.6.5
vim版本:macVim 9.0.1276
小型lua文件完全ok
我的设置配置有以下内容:
```
" 当光标滚动到距离屏幕上下还有5行的时候，自动向上或者向下滚动5行
set scrolljump=5
set scrolloff=5
```
但一旦打开超过1万行的lua文件，跳转几下，macVim直接卡住，没有任何反应，终端vim也一样
关闭此插件后，vim和macVim就能正常运行了

**Comment by silascript** [comment]
单文件一万行代码，这是传说中的"屎山"？--这规模的代码，是不是得考虑重构下代码了？

**Comment by jayli** [comment]
lua 文件写一万行？我没考虑到这种场景。

**Comment by WisdomCui** [comment]
抱歉，项目是2008的C++老项目，使用的是luatinker交互，支持lua版本也很老(5.1)，一个场景就只能单纯的加载一个lua文件，连require都不支持，所以让作者为难了，抱歉。毕竟我也不是技术大牛，重构项目这块也非常费劲。
