### ISSUE TITLE
断网机器 tab 补全

### ISSUE THREAD

**Issue by gblau** [jayli/vim-easycomplete#3]
处理 function easycomplete#CompleteFunc..<SNR>18_GetKeywords..<SNR>18_GetBufKeywordsList 时发生错误:
第    2 行:
E15: 无效的表达式: getbufinfo()

**Comment by gblau** [comment]
处理 function AutoLoadDict 时发生错误:
第    1 行:
E117: Unknown function: getbufinfo
E15: 无效的表达式: getbufinfo()
E117: Unknown function: getbufinfo
请按 ENTER 或其它命令继续
处理 function AutoLoadDict 时发生错误:
第    1 行:
E15: 无效的表达式: getbufinfo(

**Comment by jayli** [comment]
你用的vim是什么版本？需要8.0以上哦

**Comment by jayli** [comment]
easycomplete 已经完全重写，请更新使用
