### ISSUE TITLE
启用插件后vim启动过慢,open buffers这是阶段用时过长

### ISSUE THREAD

**Issue by ttly20** [jayli/vim-easycomplete#4]
这是启用时的部分日志:
351.000  005.000: clearing screen
418.000  042.000  042.000: sourcing C:\Vim\vim81\ftplugin\python.vim
431.000  001.000  001.000: sourcing C:\Vim\vim81\syntax\python.vim
439.000  000.000  000.000: sourcing C:\Vim\vim81\indent\python.vim
5920.000  5526.000: opening buffers
5921.000  001.000: BufEnter autocommands
5921.000  000.000: editing files in windows
5925.000  001.000  001.000: sourcing C:\Users\My\.vim\bundle\vim-easycomplete\autoload\easycomplete.vim
5926.000  004.000: VimEnter autocommands
5926.000  000.000: before starting main loop
5927.000  001.000: first screen update
5927.000  000.000: --- VIM STARTED ---

这是注释掉后的部分日志:
8210.000  049.000  049.000: sourcing C:\Vim\vim81\ftplugin\python.vim
8219.000  001.000  001.000: sourcing C:\Vim\vim81\syntax\python.vim
8225.000  001.000  001.000: sourcing C:\Vim\vim81\indent\python.vim
8227.000  036.000: opening buffers
8227.000  000.000: BufEnter autocommands
8227.000  000.000: editing files in windows
8228.000  001.000: VimEnter autocommands
8228.000  000.000: before starting main loop
8229.000  001.000: first screen update
8229.000  000.000: --- VIM STARTED ---

vim版本: 8.1
vim-easycomplete安装方式:vundle

**Comment by jayli** [comment]
easycomplete 已经完全重写，请更新使用
