### ISSUE TITLE
安装插件后遇到错误

### ISSUE THREAD

**Issue by lfishRhungry** [jayli/vim-easycomplete#5]
mac上使用neovim的vim-plug插件管理器
按照示例安装
打开后报错
```Error detected while processing function easycomplete#Enable:
line   25:
E121: Undefined variable: g:pmenu_scheme
Press ENTER or type command to continue
Error detected while processing function easycomplete#Enable:
line   25:
E15: Invalid expression: g:pmenu_scheme == 'default'
Press ENTER or type command to continue
```

**Comment by HandsYe** [comment]
> mac上使用neovim的vim-plug插件管理器
> 按照示例安装
> 打开后报错
> 
> ```
> line   25:
> E121: Undefined variable: g:pmenu_scheme
> Press ENTER or type command to continue
> Error detected while processing function easycomplete#Enable:
> line   25:
> E15: Invalid expression: g:pmenu_scheme == 'default'
> Press ENTER or type command to continue
> ```

centos7 安装报错
Error detected while processing function AutoLoadDict:
line    1:
E117: Unknown function: getbufinfo
E15: Invalid expression: getbufinfo()
Error detected while processing function easycomplete#Enable:
line   25:
E121: Undefined variable: g:pmenu_scheme
Press ENTER or type command to continue
Error detected while processing function easycomplete#Enable:
line   25:
E15: Invalid expression: g:pmenu_scheme == 'default'

**Comment by jayli** [comment]
不支持neovim哦

**Comment by HandsYe** [comment]
我用的就是vim


| |
Yehui
|
|
yehuitree@163.com
|
签名由网易邮箱大师定制
在2019年9月23日 23:12，lijing00333<notifications@github.com> 写道：

不支持neovim哦

**Comment by jayli** [comment]
现在再更新一下，看看是否ok

**Comment by HandsYe** [comment]
Error detected while processing function AutoLoadDict:
line    1:
E117: Unknown function: getbufinfo
E15: Invalid expression: getbufinfo()

不行

**Comment by jayli** [comment]
你用的7.4？版本太老了哦，好多函数都不支持，建议升级到vim8.0以上吧

**Comment by jayli** [comment]
easycomplete 已经完全重写，请更新使用
