### ISSUE TITLE
python 补全报错

### ISSUE THREAD

**Issue by xiaoQQya** [jayli/vim-easycomplete#53]
### 环境
* Ubuntu 21.04
* Python 3.9.4
* neovim 0.4.4
### 依赖
已安装 vim-easycomplete 和 python-language-server.
![image](https://user-images.githubusercontent.com/46475319/118438768-75000b00-b717-11eb-98ea-e6948137b4d2.png)
![image](https://user-images.githubusercontent.com/46475319/118438847-93660680-b717-11eb-9a9c-5327cdfabdf6.png)
### 错误
```
Error detected while processing function easycomplete#typing[21]..easycomplete#FireCondition[1]..<SNR>92_NormalTrigger:
line   10:
E117: Unknown function: str2list
```
![image](https://user-images.githubusercontent.com/46475319/118438893-a678d680-b717-11eb-9f4e-f069ce16f140.png)

**Comment by jayli** [comment]
已经修复

原因是 neovim 老版本缺少 str2list，作者在 [8.1.1122](https://github.com/neovim/neovim/commit/7ed4837298414488e238763953d40a4c7f2d7976) 这个 patch 中已经修复了，你更新到最新版的 neovim 也能解决这个问题。

**Comment by xiaoQQya** [comment]
> 已经修复
> 
> 原因是 neovim 老版本缺少 str2list，作者在 [8.1.1122](https://github.com/neovim/neovim/commit/7ed4837298414488e238763953d40a4c7f2d7976) 这个 patch 中已经修复了，你更新到最新版的 neovim 也能解决这个问题。

谢谢作者，更新插件后测试该问题已解决（neovim 0.4.4 好像是稳定最新版本了😶）。

不过我遇到了新的问题，问题如下：
```
Vim(let):E117: Unknown function: UltiSnips#SnippetsInCurrentScope
```
![image](https://user-images.githubusercontent.com/46475319/118746697-4440e280-b88b-11eb-8cec-adbc88b53d83.png)

通过安装 `SirVer/ultisnips` 和 `honza/vim-snippets` 两个插件已解决上述问题，不过从 `Readme` 的介绍让我认为这两个插件是可选安装的，而非必须安装的。
```
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
```

解决上述问题后测试，出现问题二：
```
Error detected while processing /home/xxx/.vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    7:
E319: No "python3" provider found. Run ":checkhealth provider"
```
![image](https://user-images.githubusercontent.com/46475319/118747707-1361ad00-b88d-11eb-9fcc-16240d2660dc.png)

通过 `checkhealth provider` 检查后发现是因为缺少 `neovim` 包，安装 [neovim](https://pypi.org/project/neovim/) 包后解决该问题。
```
pip install neovim
```
此处该问题应该是因为笔者使用 neovim 出现的（neovim 使用 `easycomplete` 除 `python-language-server` 包外，还需要依赖 `neovim` 包），使用 vim8.2 没有出现该问题。

记录一下遇到的问题，希望能为其它使用者提供一些帮助，最后感谢作者的付出，`easycomplete` 相比 `coc.nvim` 配置简单了很多，祝越来越好。

**Comment by jayli** [comment]
我用的是 neovim 0.5.0 ，所以没有出现你的这些问题，我在做一下对老版本的测试

**Comment by jayli** [comment]
`Vim(let):E117: Unknown function: UltiSnips#SnippetsInCurrentScope
`

这个问题已经修复了

**Comment by xiaoQQya** [comment]
> `Vim(let):E117: Unknown function: UltiSnips#SnippetsInCurrentScope `
> 
> 这个问题已经修复了

更新 `easycomplete` 后测试还是会出现这个问题，安装 `Plug 'SirVer/ultisnips'` 插件后就不会出现这个问题。

neovim 版本 0.4.4

**Comment by jayli** [comment]
你再试下

**Comment by xiaoQQya** [comment]
> 你再试下

更新 `easycomplete` 后测试已修复，作者辛苦了。

作者有没有增加 `Java` 补全的计划😁

**Comment by jayli** [comment]
> > 你再试下
> 
> 更新 `easycomplete` 后测试已修复，作者辛苦了。
> 
> 作者有没有增加 `Java` 补全的计划😁

已经支持 java 了

**Comment by xiaoQQya** [comment]
> > > 你再试下
> > 
> > 
> > 更新 `easycomplete` 后测试已修复，作者辛苦了。
> > 作者有没有增加 `Java` 补全的计划😁
> 
> 已经支持 java 了

好的，已经配置使用了，一切顺利😀

后面也会向其他朋友推荐的，感谢作者的辛苦付出
