### ISSUE TITLE
cpp 的补全为什么会把函数返回类型也给补全出来

### ISSUE THREAD

**Issue by Zhang1933** [jayli/vim-easycomplete#57]
# 环境
* Ubuntu 20.04 desktop
* vim  8.2
# 编译安装ccls的步骤
根据[从官方下载预编译包安装的clang+llvm](https://zhuanlan.zhihu.com/p/84876003)
```
# 下载ccls源码
git clone https://github.com/MaskRay/ccls
cd ccls
# 在ccls根目录下执行
# 第0步，下载第三方依赖(主要是rapidjson)
git submodule update --init --recursive
# 第一步，下载llvm的二进制包
# 这一步可以用任何下载工具代替，只要使用的是这个网址的结果即可
wget -c https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
# 解压二进制包
tar xf clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
# 在当前文件目录下执行cmake 执行结果保存到Release文件夹中
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/lang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04
cmake --build Release
# 开始编译并安装
cd Release
# 这里使用4线程编译，当然如果你的电脑够强的话，可以直接-j或者使用更搞核数加快编译
make -j4
# 编译完成，安装
sudo make install
```
# 问题
运行单个cpp文件，tab补全会把定义也一块补在后面。
![image](https://user-images.githubusercontent.com/56104581/119076284-dfb98b00-ba24-11eb-9896-86bf3865dcf7.png)
`str.clear()`之后,会跟着补全`->void`

**Comment by Zhang1933** [comment]
只编译安装了ccls。

**Comment by jayli** [comment]
关于 ccls 的补全，我这里只取它匹配的结果，未作任何加工，ccls 给什么样的提示，我就原样显示出来。

**Comment by Zhang1933** [comment]
## 找到一个解决办法
对于cpp文件,根据ccls的wiki，发现可以添加插件文件`im-easycomplete/autoload/easycomplete/sources/cpp.vim`中的初始化参数，将ccls默认的detailedLabel 改为false。
添加过后的`initialization_options`为：
```
function! easycomplete#sources#cpp#constructor(opt, ctx)
  if executable('ccls')
    call easycomplete#lsp#register_server({
        \ 'name': 'ccls',
        \ 'cmd': {server_info->['ccls']},
        \ 'initialization_options':{'cache': {'directory': '/tmp/ccls/cache'},'completion': {'detailedLabel': v:false}},
        \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
        \ })
  endif
endfunction
```
再次补全就没有->后面的那些了

**Comment by Zhang1933** [comment]
> ## 找到一个解决办法
> 对于cpp文件,根据ccls的wiki，发现可以添加插件文件`im-easycomplete/autoload/easycomplete/sources/cpp.vim`中的初始化参数，将ccls默认的detailedLabel 改为false。
> 添加过后的`initialization_options`为：
> 
> ```
> function! easycomplete#sources#cpp#constructor(opt, ctx)
>   if executable('ccls')
>     call easycomplete#lsp#register_server({
>         \ 'name': 'ccls',
>         \ 'cmd': {server_info->['ccls']},
>         \ 'initialization_options':{'cache': {'directory': '/tmp/ccls/cache'},'completion': {'detailedLabel': v:false}},
>         \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
>         \ })
>   endif
> endfunction
> ```
> 
> 再次补全就没有->后面的那些了

它好使了，它甚至还会把补全和定义返回值的popup窗口分开（虽然还不知道为啥
![Screenshot from 2021-05-23 12-47-23](https://user-images.githubusercontent.com/56104581/119248687-65743c80-bbc5-11eb-92d9-8ba4ac006986.png)

**Comment by jayli** [comment]
感谢你的提醒，我已经加上了这个配置。：）
