### ISSUE TITLE
有时候自动补全不完全

### ISSUE THREAD

**Issue by lfishRhungry** [jayli/vim-easycomplete#66]
在搭配go语言时，有时打开文件无法自动补全，只有文件中的缓存变量提示，有时打开又能够自动补全

**Comment by lfishRhungry** [comment]
python试了一下 也有这种情况

**Comment by jayli** [comment]
我本机没有复现，你帖下你的系统和vim版本

**Comment by lfishRhungry** [comment]
> 我本机没有复现，你帖下你的系统和vim版本

系统是manjaro 使用neovim 0.4.4
