### ISSUE TITLE
无法正确检测Vim的版本

### ISSUE THREAD

**Issue by VimWei** [jayli/vim-easycomplete#67]
我使用gvim 8.2.2825

![image](https://user-images.githubusercontent.com/25874852/121139582-7b435c00-c86b-11eb-814f-f67aa706ad7a.png)

**Comment by jayli** [comment]
![](https://gw.alicdn.com/imgextra/i1/O1CN01Sbfi8W1WzT2HWUyoO_!!6000000002859-2-tps-1096-350.png)

我现在还没有支持 gvim

**Comment by VimWei** [comment]
期待升级支持
