### ISSUE TITLE
“<c-n>" bug when writing python 

### ISSUE THREAD

**Issue by leoatchina** [jayli/vim-easycomplete#68]
I have map <c-n> to <down> in insert mode , as below
```
if Installed('vim-easycomplete') && get(g:, 'complete_engine', '') == 'ECM'
    let g:easycomplete_tab_trigger = "<tab>"
    nnoremap <M-.>  :EasyCompleteGotoDefinition<Cr>
    nnoremap <M-l>; :EasyComplete<Tab>
    nnoremap <M-l>, :EasyCompleteInstallServer<Space>
    imap <silent><expr> <C-n> pumvisible() ? "\<down>" : "\<c-n>"
    imap <silent><expr> <C-p> pumvisible() ? "\<up>"   : "\<c-p>"
```
but if I pressed <c-n> when writing python , the popup menu lost  lost of items when press `<c-n>`

If I use `<Down>` ,  this issue not happend 

![image](https://user-images.githubusercontent.com/4470821/121299317-d044a800-c927-11eb-8b0f-c6b614036240.png)

![image](https://user-images.githubusercontent.com/4470821/121299362-e0f51e00-c927-11eb-8304-d2dd697ef3d3.png)

This issue remained after I set g:easycomplete_tab_trigger to `<C-n>`

If I use `<c-j>` , `<C-k>`, it works
![image](https://user-images.githubusercontent.com/4470821/121300603-a42a2680-c929-11eb-818e-2046d823f977.png)

**Comment by leoatchina** [comment]
I have change the way I use complete_engine when I writing scripts with vim, C-j/C-k work as <Down>/<Up>, so  this issue not bother me any more.

**Comment by jayli** [comment]
This issue has been fixed!

https://github.com/jayli/vim-easycomplete/commit/37ea32cb4b982cc7487e961c81b64b30f16f67db
